[Script]
http-request ^https://mcs-mimp-web\.sf-express\.com/mcs-mimp/ script-path=https://raw.githubusercontent.com/dengfhqqq/scripts/main/loon/sfsy_loon_capture.js, requires-body=false, timeout=60, tag=SFSY_Capture_Request
http-response ^https://mcs-mimp-web\.sf-express\.com/mcs-mimp/ script-path=https://raw.githubusercontent.com/dengfhqqq/scripts/main/loon/sfsy_loon_capture.js, requires-body=false, timeout=60, tag=SFSY_Capture_Response

[MITM]
hostname = %APPEND% mcs-mimp-web.sf-express.com
